generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      sfComment
    theme:            default

    fields:
      commentable_model:   { name: Model }
      commentable_id:      { name: Id }
      _commented:          { name: Commented item }
      _author:             { name: Author }
      author:              { name: Author }
      created_at:          { name: Date }

    list:
      title:          List of the comments
      filters:        [commentable_model, commentable_id, namespace]
      sort:           [created_at, desc]
      display:        [namespace, _commented, _author, created_at, title, text]
      object_actions:
        _edit:        -
        _delete:      confirm: Are you sur you want to delete this comment ?

    edit:
      title:          Edit a comment
      display:
        "Commented object": [commentable_model, commentable_id]
        "Comment": [author_id, author_name, author_email, namespace, created_at, title, text]